# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - test
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  build: 
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go build
  release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
  test:
    machine: true
    steps: 
      - checkout
      - run: |
        echo "user:pass" > /tests/password.txt
        echo "password.txt" > /tests/mosquitto.conf
        docker run -v /tests/password.txt:/password.txt -v /tests/mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto:latest
        go test ./...
