# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - test
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
  test:
    docker:
      - image: circleci/golang:1.15
      - image: eclipse-mosquitto
    steps:
      - run: go test ./...
